services:

  consultant_api:
    container_name: consultant_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - ./consultant:/app
    ports:
      - "8001:8001"
    tty: true