services:

  pgsql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cryptobot"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/pgsql/data

  consultant_api:
    container_name: consultant_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - ./consultant:/app
    ports:
      - "8001:8001" #main.py
    tty: true