services:

  consultant_api:
    container_name: consultant_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - ./consultant:/app
    ports:
      - "8001:8001" #main.py
    tty: true
    networks:
      - pg-ext-net

networks:
  pg-ext-net:
    external:
      name: crypto-backend_pg-net