name: Deploy Consultant API

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  COIN_GECKO_API_KEY: ${{ secrets.COIN_GECKO_API_KEY }}
  COIN_GECKO_API_URL: ${{ secrets.COIN_GECKO_API_URL }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Build project for production
        run: make install-prod

      - name: Zip project for lambda
        run: make zip

      - name: Deploy
        env:
            TF_VAR_environment: prod
            TF_VAR_COIN_GECKO_API_KEY: ${{ env.COIN_GECKO_API_KEY }}
            TF_VAR_COIN_GECKO_API_URL: ${{ env.COIN_GECKO_API_URL }}
            TF_PG_USER: ${{ env.PG_USER }}
            TF_PG_PASS: ${{ env.PG_PASS }}
            TF_PG_HOST: ${{ env.PG_HOST }}
            TF_PG_DB: ${{ env.PG_DB }}
            TF_DB_URL: ${{ env.DB_URL }}
        run: |
          make tf-init
          TF_DB_URL=$TF_DB_URL make tf-apply
